//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailConfirmation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTATEntities1 : DbContext
    {
        public OTATEntities1()
            : base("name=OTATEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OCRD> OCRDs { get; set; }
        public virtual DbSet<OPOR> OPORs { get; set; }
        public virtual DbSet<ORDR> ORDRs { get; set; }
        public virtual DbSet<POR1> POR1s { get; set; }
    }
}
